version: '3'
services:
    app:
        volumes:
            - ./src/:/srv/
        environment:
            - DATABASE_HOST=database
            - DATABASE_USER=root
            - DATABASE_PASSWORD=root
            
    database:
        environment:
            - MYSQL_ROOT_PASSWORD=root